spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

sentry:
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: debug
  dsn: ${SENTRY_DSN}
  # Set traces_sample_rate to 1.0 to capture 100%
  # of transactions for tracing.
  # We recommend adjusting this value in production.
  tracesSampleRate: 1.0